# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
    percy: percy/agent@volatile

jobs:
    run_tests:
        docker:
            - image: circleci/node:9.9.0
        working_directory: ~/repo
        parallelism: 3
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run test && npm run snapshot

workflows:
    version: 2
    main:
        jobs:
            - run_tests:
                  context: dev
            - percy/finalize_all:
                  context: dev
                  requires:
                      - run_tests
